import "./globals.css";
import background from "../public/background.jpg";

import { Inter, Roboto_Mono, Poppins  } from "next/font/google";

const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  style: ["normal", "italic"],  
  weight: ["300", "400", "500", "600", "700"],  
});


const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "BingeBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Playwrite+CU:wght@100..400&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${interSans.variable} ${robotoMono.variable} ${poppins.variable} antialiased relative`}
        style={{
          backgroundImage: `url('/background.jpg')`,
          backgroundSize: "cover",
          backgroundRepeat: "repeat-y",
          backgroundAttachment: "fixed",
        }}
      >
        <div className="fixed top-0 left-0 w-full h-full bg-black/60 -z-10" />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}